services:
  bert:
    build: ./bert-as-service/ 
    ports: 
      - 5555:5555 
      - 5556:5556
      - 8000:8125
  streamlit:
    build: ./streamlit/ 
    volumes:
      - ./streamlit/:/app
    ports: 
      - 8501:8501
    networks:
      - default
    depends_on:
      - "bert"
    environment:
      - STREAMLIT_SERVER_PORT=8501 
    command: streamlit run http-app.py
